#-------------------------------------------------------------------------------------
# Manifest File to create AWS EKS Cluster in Custom VPC
#
# eksctl create cluster -f- eks_cluster_dev.yaml 
# eksctl create cluster -f- eks_cluster_prod.yaml
#
# Copyleft (c) by Sergei Ches 2024
#-------------------------------------------------------------------------------------
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: demo-prod
  region: us-east-1
  version: "1.27"

vpc:
  id: "vpc-0098d09eba11f8221"
  subnets:
    public:
      us-east-1a: {id: subnet-0279fb8f95ee9cf41} # For Load Balancer
      us-east-1b: {id: subnet-001f964b7450140bf} # For Load Balancer
    private:
      us-east-1a: {id: subnet-0fbf72c6ab6bdd614} # For Master Node
      us-east-1b: {id: subnet-0ee3a1d18e810b5dd} # For Master Node

managedNodeGroups:
- name: general
  instanceType: t3.small
  desiredCapacity: 3
  labels: {role: general}
  volumeSize: 70
  privateNetworking: true
  # amiFamily: Ubuntu2204 # This specifies that the nodes in the group will use the Ubuntu 20.04 AMI provided by Amazon EKS.

  #ssh:
  #  allow: true # enables SSH access to the nodes.
  #  publicKeyName: ssh_new_aws_devops_key # your ssh key name
