apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: demo-dev
  region: us-east-1
  version: "1.30"

vpc:
  id: "vpc-00a7ffe54fe448047"
  subnets:
    public:
      us-east-1a: {id: subnet-002e06c8d029fcdc0} # For Load Balancer
      us-east-1b: {id: subnet-0cf15a051aebd4c30} # For Load Balancer
    private:
      us-east-1a: {id: subnet-0939d27a698365035} # For Master Node
      us-east-1b: {id: subnet-09123e5cc6c551b80} # For Master Node

managedNodeGroups:
- name: general
  instanceType: t3.small
  desiredCapacity: 3
  labels: {role: general}
  volumeSize: 70
  privateNetworking: true
  # amiFamily: Ubuntu2204 # This specifies that the nodes in the group will use the Ubuntu 20.04 AMI provided by Amazon EKS.

  #ssh:
  #  allow: true # enables SSH access to the nodes.
  #  publicKeyName: ssh_new_aws_devops_key # your ssh key name
